//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\alexd\Desktop\Slicer\DynAbs\src\DynAbs.Summaries\Summaries.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DynAbs.Summaries {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SummariesParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface ISummariesListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterS([NotNull] SummariesParser.SContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitS([NotNull] SummariesParser.SContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.rv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRv([NotNull] SummariesParser.RvContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.rv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRv([NotNull] SummariesParser.RvContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.ro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRo([NotNull] SummariesParser.RoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.ro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRo([NotNull] SummariesParser.RoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR([NotNull] SummariesParser.RContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR([NotNull] SummariesParser.RContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.w"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterW([NotNull] SummariesParser.WContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.w"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitW([NotNull] SummariesParser.WContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.cn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCn([NotNull] SummariesParser.CnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.cn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCn([NotNull] SummariesParser.CnContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.null"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNull([NotNull] SummariesParser.NullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.null"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNull([NotNull] SummariesParser.NullContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.fresh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFresh([NotNull] SummariesParser.FreshContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.fresh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFresh([NotNull] SummariesParser.FreshContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.isIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsIn([NotNull] SummariesParser.IsInContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.isIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsIn([NotNull] SummariesParser.IsInContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.singleMany"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleMany([NotNull] SummariesParser.SingleManyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.singleMany"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleMany([NotNull] SummariesParser.SingleManyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.single"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle([NotNull] SummariesParser.SingleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.single"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle([NotNull] SummariesParser.SingleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.many"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMany([NotNull] SummariesParser.ManyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.many"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMany([NotNull] SummariesParser.ManyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.types"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypes([NotNull] SummariesParser.TypesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.types"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypes([NotNull] SummariesParser.TypesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] SummariesParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] SummariesParser.TypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.kinds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKinds([NotNull] SummariesParser.KindsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.kinds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKinds([NotNull] SummariesParser.KindsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKind([NotNull] SummariesParser.KindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKind([NotNull] SummariesParser.KindContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.words"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWords([NotNull] SummariesParser.WordsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.words"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWords([NotNull] SummariesParser.WordsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.elementType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementType([NotNull] SummariesParser.ElementTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.elementType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementType([NotNull] SummariesParser.ElementTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.parametricType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParametricType([NotNull] SummariesParser.ParametricTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.parametricType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParametricType([NotNull] SummariesParser.ParametricTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] SummariesParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] SummariesParser.FieldContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.anyField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnyField([NotNull] SummariesParser.AnyFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.anyField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnyField([NotNull] SummariesParser.AnyFieldContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.mc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMc([NotNull] SummariesParser.McContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.mc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMc([NotNull] SummariesParser.McContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.c"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterC([NotNull] SummariesParser.CContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.c"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitC([NotNull] SummariesParser.CContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.metf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetf([NotNull] SummariesParser.MetfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.metf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetf([NotNull] SummariesParser.MetfContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.etf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEtf([NotNull] SummariesParser.EtfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.etf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEtf([NotNull] SummariesParser.EtfContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.fa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFa([NotNull] SummariesParser.FaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.fa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFa([NotNull] SummariesParser.FaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.met"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMet([NotNull] SummariesParser.MetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.met"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMet([NotNull] SummariesParser.MetContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.et"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEt([NotNull] SummariesParser.EtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.et"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEt([NotNull] SummariesParser.EtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.bf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBf([NotNull] SummariesParser.BfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.bf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBf([NotNull] SummariesParser.BfContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterB([NotNull] SummariesParser.BContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitB([NotNull] SummariesParser.BContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.f"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF([NotNull] SummariesParser.FContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.f"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF([NotNull] SummariesParser.FContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter([NotNull] SummariesParser.FilterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter([NotNull] SummariesParser.FilterContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filterT"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilterT([NotNull] SummariesParser.FilterTContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filterT"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilterT([NotNull] SummariesParser.FilterTContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filterUT"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilterUT([NotNull] SummariesParser.FilterUTContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filterUT"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilterUT([NotNull] SummariesParser.FilterUTContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filterOT"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilterOT([NotNull] SummariesParser.FilterOTContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filterOT"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilterOT([NotNull] SummariesParser.FilterOTContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filterOK"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilterOK([NotNull] SummariesParser.FilterOKContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filterOK"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilterOK([NotNull] SummariesParser.FilterOKContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] SummariesParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] SummariesParser.NumberContext context);
}
} // namespace DynAbs.Summaries
