//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\alexd\Desktop\Slicer\DynAbs\src\DynAbs.Summaries\Summaries.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DynAbs.Summaries {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISummariesListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class SummariesBaseListener : ISummariesListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.s"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterS([NotNull] SummariesParser.SContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.s"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitS([NotNull] SummariesParser.SContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.rv"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRv([NotNull] SummariesParser.RvContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.rv"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRv([NotNull] SummariesParser.RvContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.ro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRo([NotNull] SummariesParser.RoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.ro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRo([NotNull] SummariesParser.RoContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.r"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR([NotNull] SummariesParser.RContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.r"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR([NotNull] SummariesParser.RContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.w"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterW([NotNull] SummariesParser.WContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.w"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitW([NotNull] SummariesParser.WContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.cn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCn([NotNull] SummariesParser.CnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.cn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCn([NotNull] SummariesParser.CnContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.null"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNull([NotNull] SummariesParser.NullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.null"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNull([NotNull] SummariesParser.NullContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.fresh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFresh([NotNull] SummariesParser.FreshContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.fresh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFresh([NotNull] SummariesParser.FreshContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.isIn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIsIn([NotNull] SummariesParser.IsInContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.isIn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIsIn([NotNull] SummariesParser.IsInContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.singleMany"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleMany([NotNull] SummariesParser.SingleManyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.singleMany"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleMany([NotNull] SummariesParser.SingleManyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.single"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle([NotNull] SummariesParser.SingleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.single"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle([NotNull] SummariesParser.SingleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.many"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMany([NotNull] SummariesParser.ManyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.many"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMany([NotNull] SummariesParser.ManyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.types"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypes([NotNull] SummariesParser.TypesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.types"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypes([NotNull] SummariesParser.TypesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] SummariesParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] SummariesParser.TypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.kinds"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKinds([NotNull] SummariesParser.KindsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.kinds"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKinds([NotNull] SummariesParser.KindsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.kind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKind([NotNull] SummariesParser.KindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.kind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKind([NotNull] SummariesParser.KindContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.words"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWords([NotNull] SummariesParser.WordsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.words"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWords([NotNull] SummariesParser.WordsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.elementType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementType([NotNull] SummariesParser.ElementTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.elementType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementType([NotNull] SummariesParser.ElementTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.parametricType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParametricType([NotNull] SummariesParser.ParametricTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.parametricType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParametricType([NotNull] SummariesParser.ParametricTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] SummariesParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] SummariesParser.FieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.anyField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnyField([NotNull] SummariesParser.AnyFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.anyField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnyField([NotNull] SummariesParser.AnyFieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.mc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMc([NotNull] SummariesParser.McContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.mc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMc([NotNull] SummariesParser.McContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterC([NotNull] SummariesParser.CContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitC([NotNull] SummariesParser.CContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.metf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetf([NotNull] SummariesParser.MetfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.metf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetf([NotNull] SummariesParser.MetfContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.etf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEtf([NotNull] SummariesParser.EtfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.etf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEtf([NotNull] SummariesParser.EtfContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.fa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFa([NotNull] SummariesParser.FaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.fa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFa([NotNull] SummariesParser.FaContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.met"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMet([NotNull] SummariesParser.MetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.met"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMet([NotNull] SummariesParser.MetContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.et"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEt([NotNull] SummariesParser.EtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.et"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEt([NotNull] SummariesParser.EtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.bf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBf([NotNull] SummariesParser.BfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.bf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBf([NotNull] SummariesParser.BfContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.b"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterB([NotNull] SummariesParser.BContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.b"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitB([NotNull] SummariesParser.BContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.f"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF([NotNull] SummariesParser.FContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.f"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF([NotNull] SummariesParser.FContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter([NotNull] SummariesParser.FilterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter([NotNull] SummariesParser.FilterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filterT"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilterT([NotNull] SummariesParser.FilterTContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filterT"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilterT([NotNull] SummariesParser.FilterTContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filterUT"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilterUT([NotNull] SummariesParser.FilterUTContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filterUT"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilterUT([NotNull] SummariesParser.FilterUTContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filterOT"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilterOT([NotNull] SummariesParser.FilterOTContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filterOT"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilterOT([NotNull] SummariesParser.FilterOTContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.filterOK"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilterOK([NotNull] SummariesParser.FilterOKContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.filterOK"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilterOK([NotNull] SummariesParser.FilterOKContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SummariesParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] SummariesParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SummariesParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] SummariesParser.NumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace DynAbs.Summaries
